# Generated by Django 3.0 on 2020-01-20 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200113_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 19, 58, 44, 681904)),
        ),
    ]
