# Generated by Django 3.0 on 2020-01-20 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200120_2303'),
        ('billing', '0005_auto_20200120_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingqueue',
            name='actual_time',
        ),
        migrations.RemoveField(
            model_name='billingqueue',
            name='billNo',
        ),
        migrations.AddField(
            model_name='billingqueue',
            name='billAmount',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingqueue',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 23, 3, 17, 514621)),
        ),
        migrations.DeleteModel(
            name='patientBill',
        ),
    ]
