# Generated by Django 3.0 on 2020-01-21 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200120_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 21, 12, 6, 1, 877904)),
        ),
    ]
