# Generated by Django 2.2.7 on 2020-01-23 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20200123_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 10, 41, 5, 737007)),
        ),
    ]
