# Generated by Django 3.0 on 2020-01-23 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20200123_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingqueue',
            name='isCash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 13, 1, 59, 966849)),
        ),
    ]
