# Generated by Django 3.0 on 2019-12-09 11:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20191209_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.datetime(2019, 12, 9, 11, 28, 20, 621981))),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('doctor_required', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
