# Generated by Django 3.0.2 on 2020-02-06 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_auto_20200206_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='billingRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 2, 6, 22, 28, 5, 899851))),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True)),
                ('is_Cash', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='appointmentRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('time_in', models.DateTimeField(default=datetime.datetime(2020, 2, 6, 22, 28, 5, 899851))),
                ('consultation_in', models.DateTimeField(default=datetime.datetime(2020, 2, 6, 22, 28, 5, 899851))),
                ('consultation_out', models.DateTimeField(default=datetime.datetime(2020, 2, 6, 22, 28, 5, 899851))),
                ('consultation_time', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('doctor_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
