# Generated by Django 2.2.7 on 2019-12-19 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 20, 42, 364630)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 20, 42, 364630)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 22, 20, 42, 364630)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 20, 42, 364630)),
        ),
    ]
