# Generated by Django 2.2.7 on 2019-12-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0002_auto_20191219_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 33, 18, 447976)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 33, 18, 447976)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 19, 22, 33, 18, 447976)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 22, 33, 18, 447976)),
        ),
    ]
