# Generated by Django 3.0 on 2019-12-09 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0002_auto_20191209_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 18, 48, 33, 553740)),
        ),
    ]
