# Generated by Django 3.0 on 2019-12-09 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0003_auto_20191209_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 18, 50, 34, 42230)),
        ),
    ]
