# Generated by Django 3.0 on 2019-12-19 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0003_auto_20191219_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrecords',
            name='date_time',
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 23, 35, 6, 390392)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 23, 35, 6, 390407)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 23, 35, 6, 390371)),
        ),
    ]
