# Generated by Django 3.0 on 2019-12-12 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0005_auto_20191210_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 12, 14, 37, 12, 908619)),
        ),
    ]
