# Generated by Django 3.0 on 2020-01-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0008_auto_20200122_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 329615)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 329633)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 329588)),
        ),
        migrations.AlterField(
            model_name='billingrecords',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 330329)),
        ),
    ]
