# Generated by Django 3.0 on 2020-01-23 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0009_auto_20200122_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecords',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingrecords',
            name='is_Cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 58, 18, 228626)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 58, 18, 228648)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 58, 18, 228592)),
        ),
        migrations.AlterField(
            model_name='billingrecords',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 12, 58, 18, 229546)),
        ),
    ]
