# Generated by Django 2.2.7 on 2020-01-23 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueAlgorithms', '0010_auto_20200123_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrecords',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 10, 41, 5, 734642)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 10, 41, 5, 734642)),
        ),
        migrations.AlterField(
            model_name='appointmentrecords',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 10, 41, 5, 734642)),
        ),
        migrations.AlterField(
            model_name='billingrecords',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 10, 41, 5, 734642)),
        ),
    ]
