# Generated by Django 3.0 on 2019-12-19 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 51, 0, 353988)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 51, 0, 353834)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 51, 0, 353870)),
        ),
    ]
