# Generated by Django 3.0 on 2020-01-09 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191220_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 52, 7, 17678)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 52, 7, 17361)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 52, 7, 17435)),
        ),
    ]
