# Generated by Django 3.0.2 on 2020-01-23 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('timefpp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('speciality', models.CharField(choices=[('1', 'Heart'), ('2', 'ENT'), ('3', 'Physcologist'), ('4', 'Muscle')], max_length=20)),
                ('feePerPatient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('followUpFee', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='appointmentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 1, 23, 15, 54, 21, 180974))),
                ('time_in', models.DateTimeField()),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True)),
                ('consultation_time_in', models.DateTimeField(default=datetime.datetime(2020, 1, 23, 15, 54, 21, 180974))),
                ('is_follow_up', models.BooleanField(default=False)),
                ('doctor_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
