# Generated by Django 2.2.7 on 2019-12-09 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timepp', models.DecimalField(decimal_places=1, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('speciality', models.CharField(choices=[('1', 'Heart'), ('2', 'ENT'), ('3', 'Physcologist'), ('4', 'Muscle')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='entryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='appointmentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.datetime(2019, 12, 9, 22, 12, 33, 332116))),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('doctor_required', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
