# Generated by Django 3.0 on 2019-12-09 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 11, 26, 39, 261674)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(choices=[('1', 'Heart'), ('2', 'ENT'), ('3', 'Physcologist'), ('4', 'Muscle')], max_length=20),
        ),
    ]
