# Generated by Django 3.0 on 2019-12-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentqueue',
            name='consultation_out',
        ),
        migrations.RemoveField(
            model_name='appointmentqueue',
            name='consultation_time',
        ),
        migrations.RemoveField(
            model_name='appointmentqueue',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='appointmentqueue',
            name='time_out_consultation_in',
        ),
        migrations.AddField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 19, 12, 6, 114650)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 16, 19, 12, 6, 114559)),
        ),
    ]
