# Generated by Django 3.0 on 2019-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phno', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('speciality', models.CharField(choices=[(1, 'Heart'), (2, 'ENT'), (3, 'Physcologist'), (4, 'Muscle')], max_length=20)),
            ],
        ),
    ]
