# Generated by Django 2.2.7 on 2019-12-14 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191213_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentqueue',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 12, 49, 7, 845757)),
        ),
        migrations.AddField(
            model_name='appointmentqueue',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 12, 49, 7, 845757)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 12, 49, 7, 845757)),
        ),
    ]
