# Generated by Django 3.0 on 2019-12-09 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 11, 28, 20, 620701)),
        ),
    ]
