# Generated by Django 3.0 on 2019-12-06 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_patient_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(default=datetime.datetime(2019, 12, 6, 13, 4, 56, 146505))),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('doctor_required', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor')),
                ('patint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
    ]
