# Generated by Django 2.2.7 on 2019-12-09 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191209_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 22, 18, 54, 842013)),
        ),
    ]
