# Generated by Django 3.0 on 2019-12-09 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_appointmentqueue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentqueue',
            old_name='patint',
            new_name='patient',
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 9, 8, 10, 38, 825440)),
        ),
    ]
