# Generated by Django 2.2.7 on 2019-12-14 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20191214_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentqueue',
            name='consultation_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='actual_time',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_out',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 18, 34, 14, 386105)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 18, 34, 14, 386105)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 18, 34, 14, 386105)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='time_out_consultation_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 18, 34, 14, 386105)),
        ),
    ]
