# Generated by Django 2.2.7 on 2019-12-13 05:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20191210_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 10, 38, 40, 756962)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='doctor_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor'),
        ),
    ]
