# Generated by Django 3.0 on 2019-12-10 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20191209_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 19, 16, 16, 896545)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='doctor_required',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.doctor'),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patient'),
        ),
    ]
