# Generated by Django 3.0 on 2019-12-12 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20191210_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 14, 37, 12, 907567)),
        ),
    ]
