# Generated by Django 3.0 on 2019-12-18 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20191218_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 5, 39, 398288)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 11, 5, 39, 398159)),
        ),
    ]
