# Generated by Django 3.0 on 2020-01-22 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200122_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentqueue',
            old_name='isFollowUp',
            new_name='is_follow_up',
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 21, 25, 30, 825431)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 21, 25, 30, 825303)),
        ),
    ]
