# Generated by Django 3.0 on 2020-01-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200122_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='timefpp',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 326541)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 22, 22, 6, 48, 326398)),
        ),
    ]
