# Generated by Django 2.2.7 on 2020-01-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200123_1041'),
        ('registration', '0012_auto_20200123_1302'),
    ]

    operations = [
    ]
