# Generated by Django 2.2.7 on 2020-01-23 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_merge_20200123_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentqueue',
            name='consultation_time_in',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 15, 50, 7, 581802)),
        ),
        migrations.AlterField(
            model_name='appointmentqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 15, 50, 7, 580805)),
        ),
    ]
