# Generated by Django 3.0 on 2019-12-19 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20191220_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='billingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 12, 20, 0, 51, 0, 357472))),
                ('predicted_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('actual_time', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True)),
                ('billNo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.patientBill')),
            ],
        ),
    ]
