# Generated by Django 3.0 on 2020-01-09 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingqueue',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 18, 52, 7, 27783)),
        ),
    ]
